[platformio]
default_envs = lilygo-t-display-s3-touch

[env:lilygo-t-display-s3-touch]
platform = espressif32@6.5.0
board = lilygo-t-display-s3
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
upload_speed = 921600
lib_deps =
  moononournation/GFX Library for Arduino@1.6.0
